In [ ]:
try:
    import pulp
except:
    !pip install pulp

In [51]:
from scipy.io import loadmat
import pulp
import numpy as np
import pandas as pd

In [52]:
data_mat_A = loadmat("A.mat")
print(data_mat_A)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Apr 24 00:05:18 2019', '__version__': '1.0', '__globals__': [], 'A': array([[-1. , -1. , -1. , ..., -0. , -0. , -0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [-0. , -0. , -0. , ..., -0. , -0. , -0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. , ...,  0.8, 17.9,  3. ]])}

In [53]:
df_A = data_mat_A["A"]
df_A = pd.DataFrame(df_A)

In [54]:
data_mat_b = loadmat("b.mat")
print(data_mat_b)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Apr 24 00:05:18 2019', '__version__': '1.0', '__globals__': [], 'b': array([[      -7,        5,       -5,       -2,       -1,       -1,
              -1,       -1,       -5,       -1,       -1,       -1,
              -4,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
               1,        1,        1,        1,        1,        1,
        11501312]])}

In [55]:
df_b = data_mat_b["b"]
df_b = pd.DataFrame(df_b)

In [56]:
data_mat_c = loadmat("c.mat")
print(data_mat_c)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Apr 24 00:05:18 2019', '__version__': '1.0', '__globals__': [], 'c': array([[1.8       ],
       [0.1       ],
       [0.        ],
       ...,
       [0.5679464 ],
       [1.55165589],
       [2.7305212 ]])}

In [57]:
df_c = data_mat_c["c"]
df_c = pd.DataFrame(df_c)

In [58]:
df_A.head()

,0,1,2,3,4,5,6,7,8,9,...,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189
0,-1.0,-1.0,-1.0,-1.0,-0.0,-0.0,-1.0,-0.0,-1.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
3,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
4,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0

In [59]:
df_b.head()

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,-7,5,-5,-2,-1,-1,-1,-1,-5,-1,...,1,1,1,1,1,1,1,1,1,11501312

In [60]:
df_c.head()

     0
0  1.8
1  0.1
2  0.0
3  0.2
4  2.7

In [61]:
df_b = df_b.transpose()
df_b.head()

   0
0 -7
1  5
2 -5
3 -2
4 -1

In [62]:
df_A = df_A.transpose()
df_A.head()

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,-1.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
# create variable
v_num = 1190
variables = [pulp.LpVariable('X_%d'%i, upBound = 1, lowBound = 0, cat = pulp.LpInteger) for i in range(0, v_num)]

print(variables)

# objective function
c = df_c[0].tolist()
objective = sum([c[i] * variables[i] for i in range(0, v_num)])

# subjective function
constraints = []
b = df_b[0].tolist()
for i in range(133):
    A = df_A[i].tolist()
    constraints.append(sum([A[j] * variable[j] for j in range(0, v_num)]) <= b[i])

print(len(constraints))

[X_0, X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15, X_16, X_17, X_18, X_19, X_20, X_21, X_22, X_23, X_24, X_25, X_26, X_27, X_28, X_29, X_30, X_31, X_32, X_33, X_34, X_35, X_36, X_37, X_38, X_39, X_40, X_41, X_42, X_43, X_44, X_45, X_46, X_47, X_48, X_49, X_50, X_51, X_52, X_53, X_54, X_55, X_56, X_57, X_58, X_59, X_60, X_61, X_62, X_63, X_64, X_65, X_66, X_67, X_68, X_69, X_70, X_71, X_72, X_73, X_74, X_75, X_76, X_77, X_78, X_79, X_80, X_81, X_82, X_83, X_84, X_85, X_86, X_87, X_88, X_89, X_90, X_91, X_92, X_93, X_94, X_95, X_96, X_97, X_98, X_99, X_100, X_101, X_102, X_103, X_104, X_105, X_106, X_107, X_108, X_109, X_110, X_111, X_112, X_113, X_114, X_115, X_116, X_117, X_118, X_119, X_120, X_121, X_122, X_123, X_124, X_125, X_126, X_127, X_128, X_129, X_130, X_131, X_132, X_133, X_134, X_135, X_136, X_137, X_138, X_139, X_140, X_141, X_142, X_143, X_144, X_145, X_146, X_147, X_148, X_149, X_150, X_151, X_152, X_153, X_154, X_155, X_156, X_157, X_158, X_159, X_160, X_161, X_162, X_163, X_164, X_165, X_166, X_167, X_168, X_169, X_170, X_171, X_172, X_173, X_174, X_175, X_176, X_177, X_178, X_179, X_180, X_181, X_182, X_183, X_184, X_185, X_186, X_187, X_188, X_189, X_190, X_191, X_192, X_193, X_194, X_195, X_196, X_197, X_198, X_199, X_200, X_201, X_202, X_203, X_204, X_205, X_206, X_207, X_208, X_209, X_210, X_211, X_212, X_213, X_214, X_215, X_216, X_217, X_218, X_219, X_220, X_221, X_222, X_223, X_224, X_225, X_226, X_227, X_228, X_229, X_230, X_231, X_232, X_233, X_234, X_235, X_236, X_237, X_238, X_239, X_240, X_241, X_242, X_243, X_244, X_245, X_246, X_247, X_248, X_249, X_250, X_251, X_252, X_253, X_254, X_255, X_256, X_257, X_258, X_259, X_260, X_261, X_262, X_263, X_264, X_265, X_266, X_267, X_268, X_269, X_270, X_271, X_272, X_273, X_274, X_275, X_276, X_277, X_278, X_279, X_280, X_281, X_282, X_283, X_284, X_285, X_286, X_287, X_288, X_289, X_290, X_291, X_292, X_293, X_294, X_295, X_296, X_297, X_298, X_299, X_300, X_301, X_302, X_303, X_304, X_305, X_306, X_307, X_308, X_309, X_310, X_311, X_312, X_313, X_314, X_315, X_316, X_317, X_318, X_319, X_320, X_321, X_322, X_323, X_324, X_325, X_326, X_327, X_328, X_329, X_330, X_331, X_332, X_333, X_334, X_335, X_336, X_337, X_338, X_339, X_340, X_341, X_342, X_343, X_344, X_345, X_346, X_347, X_348, X_349, X_350, X_351, X_352, X_353, X_354, X_355, X_356, X_357, X_358, X_359, X_360, X_361, X_362, X_363, X_364, X_365, X_366, X_367, X_368, X_369, X_370, X_371, X_372, X_373, X_374, X_375, X_376, X_377, X_378, X_379, X_380, X_381, X_382, X_383, X_384, X_385, X_386, X_387, X_388, X_389, X_390, X_391, X_392, X_393, X_394, X_395, X_396, X_397, X_398, X_399, X_400, X_401, X_402, X_403, X_404, X_405, X_406, X_407, X_408, X_409, X_410, X_411, X_412, X_413, X_414, X_415, X_416, X_417, X_418, X_419, X_420, X_421, X_422, X_423, X_424, X_425, X_426, X_427, X_428, X_429, X_430, X_431, X_432, X_433, X_434, X_435, X_436, X_437, X_438, X_439, X_440, X_441, X_442, X_443, X_444, X_445, X_446, X_447, X_448, X_449, X_450, X_451, X_452, X_453, X_454, X_455, X_456, X_457, X_458, X_459, X_460, X_461, X_462, X_463, X_464, X_465, X_466, X_467, X_468, X_469, X_470, X_471, X_472, X_473, X_474, X_475, X_476, X_477, X_478, X_479, X_480, X_481, X_482, X_483, X_484, X_485, X_486, X_487, X_488, X_489, X_490, X_491, X_492, X_493, X_494, X_495, X_496, X_497, X_498, X_499, X_500, X_501, X_502, X_503, X_504, X_505, X_506, X_507, X_508, X_509, X_510, X_511, X_512, X_513, X_514, X_515, X_516, X_517, X_518, X_519, X_520, X_521, X_522, X_523, X_524, X_525, X_526, X_527, X_528, X_529, X_530, X_531, X_532, X_533, X_534, X_535, X_536, X_537, X_538, X_539, X_540, X_541, X_542, X_543, X_544, X_545, X_546, X_547, X_548, X_549, X_550, X_551, X_552, X_553, X_554, X_555, X_556, X_557, X_558, X_559, X_560, X_561, X_562, X_563, X_564, X_565, X_566, X_567, X_568, X_569, X_570, X_571, X_572, X_573, X_574, X_575, X_576, X_577, X_578, X_579, X_580, X_581, X_582, X_583, X_584, X_585, X_586, X_587, X_588, X_589, X_590, X_591, X_592, X_593, X_594, X_595, X_596, X_597, X_598, X_599, X_600, X_601, X_602, X_603, X_604, X_605, X_606, X_607, X_608, X_609, X_610, X_611, X_612, X_613, X_614, X_615, X_616, X_617, X_618, X_619, X_620, X_621, X_622, X_623, X_624, X_625, X_626, X_627, X_628, X_629, X_630, X_631, X_632, X_633, X_634, X_635, X_636, X_637, X_638, X_639, X_640, X_641, X_642, X_643, X_644, X_645, X_646, X_647, X_648, X_649, X_650, X_651, X_652, X_653, X_654, X_655, X_656, X_657, X_658, X_659, X_660, X_661, X_662, X_663, X_664, X_665, X_666, X_667, X_668, X_669, X_670, X_671, X_672, X_673, X_674, X_675, X_676, X_677, X_678, X_679, X_680, X_681, X_682, X_683, X_684, X_685, X_686, X_687, X_688, X_689, X_690, X_691, X_692, X_693, X_694, X_695, X_696, X_697, X_698, X_699, X_700, X_701, X_702, X_703, X_704, X_705, X_706, X_707, X_708, X_709, X_710, X_711, X_712, X_713, X_714, X_715, X_716, X_717, X_718, X_719, X_720, X_721, X_722, X_723, X_724, X_725, X_726, X_727, X_728, X_729, X_730, X_731, X_732, X_733, X_734, X_735, X_736, X_737, X_738, X_739, X_740, X_741, X_742, X_743, X_744, X_745, X_746, X_747, X_748, X_749, X_750, X_751, X_752, X_753, X_754, X_755, X_756, X_757, X_758, X_759, X_760, X_761, X_762, X_763, X_764, X_765, X_766, X_767, X_768, X_769, X_770, X_771, X_772, X_773, X_774, X_775, X_776, X_777, X_778, X_779, X_780, X_781, X_782, X_783, X_784, X_785, X_786, X_787, X_788, X_789, X_790, X_791, X_792, X_793, X_794, X_795, X_796, X_797, X_798, X_799, X_800, X_801, X_802, X_803, X_804, X_805, X_806, X_807, X_808, X_809, X_810, X_811, X_812, X_813, X_814, X_815, X_816, X_817, X_818, X_819, X_820, X_821, X_822, X_823, X_824, X_825, X_826, X_827, X_828, X_829, X_830, X_831, X_832, X_833, X_834, X_835, X_836, X_837, X_838, X_839, X_840, X_841, X_842, X_843, X_844, X_845, X_846, X_847, X_848, X_849, X_850, X_851, X_852, X_853, X_854, X_855, X_856, X_857, X_858, X_859, X_860, X_861, X_862, X_863, X_864, X_865, X_866, X_867, X_868, X_869, X_870, X_871, X_872, X_873, X_874, X_875, X_876, X_877, X_878, X_879, X_880, X_881, X_882, X_883, X_884, X_885, X_886, X_887, X_888, X_889, X_890, X_891, X_892, X_893, X_894, X_895, X_896, X_897, X_898, X_899, X_900, X_901, X_902, X_903, X_904, X_905, X_906, X_907, X_908, X_909, X_910, X_911, X_912, X_913, X_914, X_915, X_916, X_917, X_918, X_919, X_920, X_921, X_922, X_923, X_924, X_925, X_926, X_927, X_928, X_929, X_930, X_931, X_932, X_933, X_934, X_935, X_936, X_937, X_938, X_939, X_940, X_941, X_942, X_943, X_944, X_945, X_946, X_947, X_948, X_949, X_950, X_951, X_952, X_953, X_954, X_955, X_956, X_957, X_958, X_959, X_960, X_961, X_962, X_963, X_964, X_965, X_966, X_967, X_968, X_969, X_970, X_971, X_972, X_973, X_974, X_975, X_976, X_977, X_978, X_979, X_980, X_981, X_982, X_983, X_984, X_985, X_986, X_987, X_988, X_989, X_990, X_991, X_992, X_993, X_994, X_995, X_996, X_997, X_998, X_999, X_1000, X_1001, X_1002, X_1003, X_1004, X_1005, X_1006, X_1007, X_1008, X_1009, X_1010, X_1011, X_1012, X_1013, X_1014, X_1015, X_1016, X_1017, X_1018, X_1019, X_1020, X_1021, X_1022, X_1023, X_1024, X_1025, X_1026, X_1027, X_1028, X_1029, X_1030, X_1031, X_1032, X_1033, X_1034, X_1035, X_1036, X_1037, X_1038, X_1039, X_1040, X_1041, X_1042, X_1043, X_1044, X_1045, X_1046, X_1047, X_1048, X_1049, X_1050, X_1051, X_1052, X_1053, X_1054, X_1055, X_1056, X_1057, X_1058, X_1059, X_1060, X_1061, X_1062, X_1063, X_1064, X_1065, X_1066, X_1067, X_1068, X_1069, X_1070, X_1071, X_1072, X_1073, X_1074, X_1075, X_1076, X_1077, X_1078, X_1079, X_1080, X_1081, X_1082, X_1083, X_1084, X_1085, X_1086, X_1087, X_1088, X_1089, X_1090, X_1091, X_1092, X_1093, X_1094, X_1095, X_1096, X_1097, X_1098, X_1099, X_1100, X_1101, X_1102, X_1103, X_1104, X_1105, X_1106, X_1107, X_1108, X_1109, X_1110, X_1111, X_1112, X_1113, X_1114, X_1115, X_1116, X_1117, X_1118, X_1119, X_1120, X_1121, X_1122, X_1123, X_1124, X_1125, X_1126, X_1127, X_1128, X_1129, X_1130, X_1131, X_1132, X_1133, X_1134, X_1135, X_1136, X_1137, X_1138, X_1139, X_1140, X_1141, X_1142, X_1143, X_1144, X_1145, X_1146, X_1147, X_1148, X_1149, X_1150, X_1151, X_1152, X_1153, X_1154, X_1155, X_1156, X_1157, X_1158, X_1159, X_1160, X_1161, X_1162, X_1163, X_1164, X_1165, X_1166, X_1167, X_1168, X_1169, X_1170, X_1171, X_1172, X_1173, X_1174, X_1175, X_1176, X_1177, X_1178, X_1179, X_1180, X_1181, X_1182, X_1183, X_1184, X_1185, X_1186, X_1187, X_1188, X_1189]

133

In [81]:
def solve_integer_LP_max(objective, subjective):
    # building problem
    problem = pulp.LpProblem('Integer Programming', pulp.LpMaximize)
    problem += objective
    for constraint in subjective:
        problem += constraint
    # solving problem
    solution = problem.solve()
    if solution != 1:
        print("Error in solve_integer_LP_max")
        return None
    else:
        # return a list of solutions, 1 if we select, 0 otherwise
        return [v.varValue.real for v in problem.variables()]

In [82]:
res = solve_integer_LP_max(objective, constraints)
print(res)

[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]